# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 05:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import festivus.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('event_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=30)),
                ('budget', models.IntegerField(default=0)),
                ('currency', models.CharField(choices=[('USD', '$'), ('LBP', 'LL')], default='USD', max_length=3)),
                ('gift_card', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2016, 2016), (2017, 2017)], default=2017, verbose_name='year')),
                ('month', models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], default='JAN', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('currency', models.CharField(choices=[('USD', '$'), ('LBP', 'LL')], default='USD', max_length=3)),
                ('enrolled', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10)),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('E', 'Engaged'), ('D', 'Married'), ('W', 'Windowed'), ('C', 'Complicated')], default='S', max_length=10)),
                ('squad_member', models.BooleanField(default=False)),
                ('food_allergies', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=8, validators=[festivus.models.validate_phone])),
                ('description', models.CharField(blank=True, max_length=200)),
                ('rating', models.IntegerField(choices=[(1, 'Unless Necessary'), (2, 'Good Enough'), (3, 'Average'), (4, 'Great'), (5, 'Amazing')], default=3)),
                ('comment', models.TextField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representative', to='festivus.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], default='D', max_length=1)),
                ('amount', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('currency', models.CharField(choices=[('USD', '$'), ('LBP', 'LL')], default='USD', max_length=3)),
                ('transaction_date', models.DateField(default=datetime.date.today)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('note', models.TextField(blank=True, max_length=400)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivus.Event')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivus.PlaceCategory'),
        ),
        migrations.AddField(
            model_name='person',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivus.Team'),
        ),
        migrations.AddField(
            model_name='payment',
            name='collected_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_by', to='festivus.Person'),
        ),
        migrations.AddField(
            model_name='payment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivus.Person'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivus.EventType'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_organizer', to='festivus.Person'),
        ),
        migrations.AddField(
            model_name='event',
            name='squad',
            field=models.ManyToManyField(related_name='squad', to='festivus.Person'),
        ),
        migrations.AddField(
            model_name='event',
            name='targets',
            field=models.ManyToManyField(related_name='targets', to='festivus.Person'),
        ),
    ]
