# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivus', '0003_auto_20170604_0859'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlaceCategory',
            new_name='PlaceClassification',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='category',
            new_name='classification',
        ),
    ]
