# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivus', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('USD', '\\$'), ('LBP', 'LL')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6),
        ),
        migrations.AlterField(
            model_name='payment',
            name='year',
            field=models.IntegerField(choices=[(2016, 2016), (2017, 2017)], default=2017, verbose_name='year'),
        ),
    ]
