# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivus', '0004_auto_20170604_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
