# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivus', '0004_auto_20170530_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='enrolled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('USD', '$'), ('LBP', 'LL')], default='USD', max_length=3),
        ),
    ]
