# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivus', '0005_auto_20170604_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='enrolled',
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.FileField(blank=True, upload_to='invoices'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('M', 'Membership'), ('E', 'Expense')], default='M', max_length=20),
        ),
    ]
