# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import festivus.models


class Migration(migrations.Migration):

    dependencies = [
        ('festivus', '0005_auto_20170530_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.IntegerField(validators=[festivus.models.validatePhone])),
                ('description', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivus.PlaceCategory')),
            ],
        ),
    ]
