# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import festivus.models


class Migration(migrations.Migration):

    dependencies = [
        ('festivus', '0006_placecategory_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.IntegerField(validators=[festivus.models.validatePhone])),
                ('description', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivus.PlaceCategory')),
            ],
        ),
        migrations.RemoveField(
            model_name='places',
            name='category',
        ),
        migrations.DeleteModel(
            name='Places',
        ),
    ]
