# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festivus', '0006_auto_20170604_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2016, 2016), (2017, 2017)], default=2017, verbose_name='year')),
                ('month', models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], default='JAN', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('currency', models.CharField(choices=[('USD', '$'), ('LBP', 'LL')], default='USD', max_length=3)),
                ('notes', models.TextField(blank=True, max_length=400)),
                ('collected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_by', to='festivus.Person')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivus.Person')),
            ],
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='comment',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='collected_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='month',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='person',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='year',
        ),
        migrations.AddField(
            model_name='payment',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='festivus.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
