# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivus', '0007_auto_20170530_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='john.smith@murex.com', max_length=254),
            preserve_default=False,
        ),
    ]
