# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festivus', '0007_auto_20170604_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='festivus.Event'),
        ),
    ]
