# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivus', '0008_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Unless Necessary'), (2, 'Good Enough'), (3, 'Average'), (4, 'Great'), (5, 'Amazing')], default=3),
        ),
    ]
