# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import festivus.models


class Migration(migrations.Migration):

    dependencies = [
        ('festivus', '0009_place_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='phone',
            field=models.CharField(max_length=8, validators=[festivus.models.validatePhone]),
        ),
    ]
