# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivus', '0010_transaction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=10),
        ),
    ]
