# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import festivus.models


class Migration(migrations.Migration):

    dependencies = [
        ('festivus', '0011_auto_20170530_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='victim',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='festivus.Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_organizer', to='festivus.Person'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='phone',
            field=models.CharField(max_length=8, null=True, validators=[festivus.models.validatePhone]),
        ),
    ]
