# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivus', '0011_auto_20170605_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=10, max_digits=15),
        ),
    ]
