# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import festivus.models


class Migration(migrations.Migration):

    dependencies = [
        ('festivus', '0012_auto_20170530_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='comment',
            field=models.TextField(blank=True, default='this is a comment', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, default='Ashrafieh', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='description',
            field=models.CharField(blank=True, default='Description', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, default='Hamra', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='comment',
            field=models.TextField(blank=True, default='Comment', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.CharField(blank=True, default='desc', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=8, validators=[festivus.models.validatePhone]),
            preserve_default=False,
        ),
    ]
