# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 04:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festivus', '0013_auto_20170531_0426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], default='D', max_length=1)),
                ('amount', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('currency', models.CharField(choices=[('USD', '$'), ('LBP', 'LL')], default='USD', max_length=3)),
                ('transaction_date', models.DateField(default=datetime.date.today)),
                ('note', models.TextField(blank=True, max_length=400)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivus.Event')),
            ],
        ),
    ]
