# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivus', '0014_auto_20170609_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='order_from',
            field=models.ManyToManyField(related_name='places', to='festivus.Place'),
        ),
        migrations.AddField(
            model_name='person',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='marital_status',
            field=models.CharField(choices=[('S', 'Single'), ('E', 'Engaged'), ('D', 'Married'), ('W', 'Windowed'), ('C', "It's Complicated")], default='S', max_length=10),
        ),
    ]
