# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivus', '0014_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='Bday Celebration', max_length=30),
            preserve_default=False,
        ),
    ]
