# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivus', '0015_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='comment',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
